name: ello_ai_server
description: Dart gRPC server for Ello AI chat and LLM services (dev only)
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: {}

dev_dependencies:
  grpc: ^4.1.0
  protobuf: ^4.1.0
  uuid: ^4.2.1
  logging: ^1.2.0
  args: ^2.4.2
  build_runner: ^2.4.7
  protoc_plugin: ^22.3.0
  test: ^1.24.9
  lints: ^5.1.1

# Generate protobuf files
executables:
  ello_ai_server:
