name: ello_ai
description: A sleek, modern AI chat assistant for every platform.
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  http: ^1.2.0
  flutter_markdown: ^0.6.18
  flutter_localizations:
    sdk: flutter
  intl: any

flutter:
  uses-material-design: true

