name: ello_ai
description: A sleek, modern AI chat assistant for every platform.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  http: ^1.2.0
  flutter_markdown: ^0.6.18
  flutter_highlighter: ^0.1.1
  flutter_localizations:
    sdk: flutter
  intl: any
  grpc: ^3.2.4 # Using standard gRPC for Cloud Run communication
  protobuf: ^3.1.0 # Version compatible with protoc_plugin
  fixnum: ^1.1.0
  uuid: ^4.3.3 # For generating unique message IDs
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  protoc_plugin: ^21.1.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
