// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/llm_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request format for chat completion
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Temperature   float32                `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_proto_llm_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_llm_service_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ChatRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ChatRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Single message in a conversation
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_llm_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_llm_service_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Streaming response format
type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Choice        *Choice                `protobuf:"bytes,3,opt,name=choice,proto3" json:"choice,omitempty"`
	Created       uint64                 `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Done          bool                   `protobuf:"varint,5,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_proto_llm_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_proto_llm_service_proto_rawDescGZIP(), []int{2}
}

func (x *ChatResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatResponse) GetChoice() *Choice {
	if x != nil {
		return x.Choice
	}
	return nil
}

func (x *ChatResponse) GetCreated() uint64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ChatResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

// Complete response (non-streaming)
type ChatCompletionResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Model                 string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Choices               []*Choice              `protobuf:"bytes,3,rep,name=choices,proto3" json:"choices,omitempty"`
	Created               uint64                 `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	UsagePromptTokens     uint64                 `protobuf:"varint,5,opt,name=usage_prompt_tokens,json=usagePromptTokens,proto3" json:"usage_prompt_tokens,omitempty"`
	UsageCompletionTokens uint64                 `protobuf:"varint,6,opt,name=usage_completion_tokens,json=usageCompletionTokens,proto3" json:"usage_completion_tokens,omitempty"`
	UsageTotalTokens      uint64                 `protobuf:"varint,7,opt,name=usage_total_tokens,json=usageTotalTokens,proto3" json:"usage_total_tokens,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ChatCompletionResponse) Reset() {
	*x = ChatCompletionResponse{}
	mi := &file_proto_llm_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionResponse) ProtoMessage() {}

func (x *ChatCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionResponse.ProtoReflect.Descriptor instead.
func (*ChatCompletionResponse) Descriptor() ([]byte, []int) {
	return file_proto_llm_service_proto_rawDescGZIP(), []int{3}
}

func (x *ChatCompletionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatCompletionResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionResponse) GetChoices() []*Choice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *ChatCompletionResponse) GetCreated() uint64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ChatCompletionResponse) GetUsagePromptTokens() uint64 {
	if x != nil {
		return x.UsagePromptTokens
	}
	return 0
}

func (x *ChatCompletionResponse) GetUsageCompletionTokens() uint64 {
	if x != nil {
		return x.UsageCompletionTokens
	}
	return 0
}

func (x *ChatCompletionResponse) GetUsageTotalTokens() uint64 {
	if x != nil {
		return x.UsageTotalTokens
	}
	return 0
}

// Response choice containing generated content
type Choice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	FinishReason  string                 `protobuf:"bytes,2,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	Index         int32                  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Choice) Reset() {
	*x = Choice{}
	mi := &file_proto_llm_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Choice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Choice) ProtoMessage() {}

func (x *Choice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_llm_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Choice.ProtoReflect.Descriptor instead.
func (*Choice) Descriptor() ([]byte, []int) {
	return file_proto_llm_service_proto_rawDescGZIP(), []int{4}
}

func (x *Choice) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Choice) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *Choice) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

var File_proto_llm_service_proto protoreflect.FileDescriptor

const file_proto_llm_service_proto_rawDesc = "" +
	"\n" +
	"\x17proto/llm_service.proto\x12\vllm_gateway\"\xaf\x01\n" +
	"\vChatRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x120\n" +
	"\bmessages\x18\x02 \x03(\v2\x14.llm_gateway.MessageR\bmessages\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x8f\x01\n" +
	"\fChatResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12+\n" +
	"\x06choice\x18\x03 \x01(\v2\x13.llm_gateway.ChoiceR\x06choice\x12\x18\n" +
	"\acreated\x18\x04 \x01(\x04R\acreated\x12\x12\n" +
	"\x04done\x18\x05 \x01(\bR\x04done\"\x9d\x02\n" +
	"\x16ChatCompletionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12-\n" +
	"\achoices\x18\x03 \x03(\v2\x13.llm_gateway.ChoiceR\achoices\x12\x18\n" +
	"\acreated\x18\x04 \x01(\x04R\acreated\x12.\n" +
	"\x13usage_prompt_tokens\x18\x05 \x01(\x04R\x11usagePromptTokens\x126\n" +
	"\x17usage_completion_tokens\x18\x06 \x01(\x04R\x15usageCompletionTokens\x12,\n" +
	"\x12usage_total_tokens\x18\a \x01(\x04R\x10usageTotalTokens\"s\n" +
	"\x06Choice\x12.\n" +
	"\amessage\x18\x01 \x01(\v2\x14.llm_gateway.MessageR\amessage\x12#\n" +
	"\rfinish_reason\x18\x02 \x01(\tR\ffinishReason\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x05R\x05index2\xb0\x01\n" +
	"\n" +
	"LLMService\x12O\n" +
	"\x14ChatCompletionStream\x12\x18.llm_gateway.ChatRequest\x1a\x19.llm_gateway.ChatResponse\"\x000\x01\x12Q\n" +
	"\x0eChatCompletion\x12\x18.llm_gateway.ChatRequest\x1a#.llm_gateway.ChatCompletionResponse\"\x00B\x16Z\x14ello.ai/server/protob\x06proto3"

var (
	file_proto_llm_service_proto_rawDescOnce sync.Once
	file_proto_llm_service_proto_rawDescData []byte
)

func file_proto_llm_service_proto_rawDescGZIP() []byte {
	file_proto_llm_service_proto_rawDescOnce.Do(func() {
		file_proto_llm_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_llm_service_proto_rawDesc), len(file_proto_llm_service_proto_rawDesc)))
	})
	return file_proto_llm_service_proto_rawDescData
}

var file_proto_llm_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_llm_service_proto_goTypes = []any{
	(*ChatRequest)(nil),            // 0: llm_gateway.ChatRequest
	(*Message)(nil),                // 1: llm_gateway.Message
	(*ChatResponse)(nil),           // 2: llm_gateway.ChatResponse
	(*ChatCompletionResponse)(nil), // 3: llm_gateway.ChatCompletionResponse
	(*Choice)(nil),                 // 4: llm_gateway.Choice
}
var file_proto_llm_service_proto_depIdxs = []int32{
	1, // 0: llm_gateway.ChatRequest.messages:type_name -> llm_gateway.Message
	4, // 1: llm_gateway.ChatResponse.choice:type_name -> llm_gateway.Choice
	4, // 2: llm_gateway.ChatCompletionResponse.choices:type_name -> llm_gateway.Choice
	1, // 3: llm_gateway.Choice.message:type_name -> llm_gateway.Message
	0, // 4: llm_gateway.LLMService.ChatCompletionStream:input_type -> llm_gateway.ChatRequest
	0, // 5: llm_gateway.LLMService.ChatCompletion:input_type -> llm_gateway.ChatRequest
	2, // 6: llm_gateway.LLMService.ChatCompletionStream:output_type -> llm_gateway.ChatResponse
	3, // 7: llm_gateway.LLMService.ChatCompletion:output_type -> llm_gateway.ChatCompletionResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_llm_service_proto_init() }
func file_proto_llm_service_proto_init() {
	if File_proto_llm_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_llm_service_proto_rawDesc), len(file_proto_llm_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_llm_service_proto_goTypes,
		DependencyIndexes: file_proto_llm_service_proto_depIdxs,
		MessageInfos:      file_proto_llm_service_proto_msgTypes,
	}.Build()
	File_proto_llm_service_proto = out.File
	file_proto_llm_service_proto_goTypes = nil
	file_proto_llm_service_proto_depIdxs = nil
}
