name: Pull Request Checks

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]

# Prevents concurrent runs on the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  flutter-checks:
    name: Flutter Lint & Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"
          channel: "stable"
          cache: true

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Verify the system
        run: flutter doctor

      - name: Generate protobuf files
        run: |
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analyze Flutter code
        run: flutter analyze --fatal-infos --fatal-warnings

      - name: Check Flutter formatting
        run: dart format --set-exit-if-changed .

      - name: Run Flutter tests
        run: flutter test --coverage --reporter=github

      - name: Upload coverage to Codecov (optional)
        if: success()
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: flutter
          name: flutter-coverage
        continue-on-error: true

  build-check:
    name: Build Verification
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [flutter-checks]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"
          channel: "stable"
          cache: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Generate protobuf files
        run: |
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Flutter app (Web)
        run: flutter build web --no-pub

      - name: Build Flutter app (Android APK)
        run: flutter build apk --debug --no-pub

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"
        continue-on-error: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
        continue-on-error: true

  summary:
    name: PR Status Summary
    runs-on: ubuntu-latest
    needs: [flutter-checks, build-check]
    if: always()

    steps:
      - name: Check all job results
        run: |
          echo "Flutter checks: ${{ needs.flutter-checks.result }}"
          echo "Build check: ${{ needs.build-check.result }}"

          if [[ "${{ needs.flutter-checks.result }}" != "success" || "${{ needs.build-check.result }}" != "success" ]]; then
            echo "❌ One or more checks failed. PR cannot be merged."
            exit 1
          else
            echo "✅ All checks passed. PR is ready for review."
          fi
